version: '3.1'
services:

   hub-service-db:
    container_name: hub-service-db
    image: mongo
    restart: always
    ports:
      - 27017:27017

   hub-service:
    container_name: hub-service-api
    build: .
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDBConfig__Host: hub-service-db
    depends_on:
      - hub-service-db
    volumes:
     - ./hub.service:/hub.service
