version: '3.1'
services:

   product-service-db:
    container_name: product-service-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/dump/:/dump/:rw
      - ./db/:/docker-entrypoint-initdb.d/:ro  
      
   hub-service:
    container_name: product-service-api
    image: loanburger/dotnet-mongo-docker:latest
    build: 
      context: ./product.service
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDBConfig__Host: product-service-db
    depends_on:
      - product-service-db
