version: '3.9'
services:

   hub-service-db:
    container_name: hub-service-db
    image: mongo
    restart: always
    ports:
      - 27017:27017

   hub-service-api:
    container_name: hub-service-api
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      MongoDBConfig__Host: mongo
    depends_on:
      - hub-service-db
